pipeline {
    agent any
    
    environment {
        SOURCE_DIR                 = 'examples'
        BUCKET_NAME                = 'jenkins-hermit-artifacts-zip'
        AWS_DEFAULT_REGION         = 'eu-north-1'
    }

    stages {
        stage('Clone Repo') {
            steps {
                script {
                    checkout([$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[url: 'https://github.com/facebookexperimental/hermit']]])
                }
            }
        }
    
        stage('Zip Artifacts') {
            steps {
                sshagent(credentials : ['d57de4e3-584b-405c-b599-919d73fa7448']) {
                    sh 'ssh -v denizicinn@hotmail.com'
        }
            }
        }
  }

    post {
        always {
            sh "rm -rf *"
        }
    }
}