pipeline {
    agent any
    
    environment {
        SOURCE_DIR                 = 'examples'
        BUCKET_NAME                = 'jenkins-hermit-artifacts-zip'
        AWS_DEFAULT_REGION         = 'eu-north-1'
    }

    stages {
        stage('SSH') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: '	d57de4e3-584b-405c-b599-919d73fa7448', keyFileVariable: 'MY_SSH_KEY')]) {
                script{
                    sh 'ssh -i $MY_SSH_KEY vagrant@192.168.50.4'
        }
      }
   }
}
        stage('Do sth') {
            steps {
                script {                    
                    sh "echo 'test123'"
                    sh "mkdir exampledir"
                }
            }
        }
  }
}